name: CR
on:
  push:
    branches:
    - "main"
    - "beta"

concurrency:
  group: "release"
  cancel-in-progress: true

permissions:
  id-token: write

jobs:
  release:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache: "npm"
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Generate Release
      run: npx semantic-release
